// Code generated by ogen, DO NOT EDIT.
package api

type AcceptSessionRes interface {
	acceptSessionRes()
}

type AcceptWorkgroupInvitationRes interface {
	acceptWorkgroupInvitationRes()
}

type AddTunnelGrantRes interface {
	addTunnelGrantRes()
}

type AddWorkgroupMemberRes interface {
	addWorkgroupMemberRes()
}

type AdminCloseSessionRes interface {
	adminCloseSessionRes()
}

type ChangePasswordRes interface {
	changePasswordRes()
}

type ChangeWorkgroupMembershipRoleRes interface {
	changeWorkgroupMembershipRoleRes()
}

type CloseSessionRes interface {
	closeSessionRes()
}

type ConnectTunnelRes interface {
	connectTunnelRes()
}

type CreateAccountRes interface {
	createAccountRes()
}

type CreateContractRes interface {
	createContractRes()
}

type CreateOrganizationRes interface {
	createOrganizationRes()
}

type CreateTunnelRes interface {
	createTunnelRes()
}

type CreateWorkgroupRes interface {
	createWorkgroupRes()
}

type DeclineWorkgroupInvitationRes interface {
	declineWorkgroupInvitationRes()
}

type DeleteAccountRes interface {
	deleteAccountRes()
}

type DeleteContractRes interface {
	deleteContractRes()
}

type DeleteOrganizationRes interface {
	deleteOrganizationRes()
}

type DeleteTunnelAttachmentRes interface {
	deleteTunnelAttachmentRes()
}

type DeleteTunnelRes interface {
	deleteTunnelRes()
}

type DeleteTunnelServeRes interface {
	deleteTunnelServeRes()
}

type DeleteWorkgroupRes interface {
	deleteWorkgroupRes()
}

type DetachDialerAttachmentRes interface {
	detachDialerAttachmentRes()
}

type DisableEnvironmentRes interface {
	disableEnvironmentRes()
}

type EnableEnvironmentRes interface {
	enableEnvironmentRes()
}

type GetAccountTokenRes interface {
	getAccountTokenRes()
}

type GetActiveDialerAttachmentRes interface {
	getActiveDialerAttachmentRes()
}

type GetAdvertisementRes interface {
	getAdvertisementRes()
}

type GetContractRes interface {
	getContractRes()
}

type GetDashboardActivityRes interface {
	getDashboardActivityRes()
}

type GetDashboardEnvironmentsRes interface {
	getDashboardEnvironmentsRes()
}

type GetDashboardSummaryRes interface {
	getDashboardSummaryRes()
}

type GetEnvironmentRes interface {
	getEnvironmentRes()
}

type GetSessionRes interface {
	getSessionRes()
}

type GetTunnelRes interface {
	getTunnelRes()
}

type GetTunnelServeRes interface {
	getTunnelServeRes()
}

type GetVersionRes interface {
	getVersionRes()
}

type GetWorkgroupRes interface {
	getWorkgroupRes()
}

type GetWorkgroupsActivityRes interface {
	getWorkgroupsActivityRes()
}

type HeartbeatEnvironmentRes interface {
	heartbeatEnvironmentRes()
}

type HeartbeatTunnelAttachmentRes interface {
	heartbeatTunnelAttachmentRes()
}

type HeartbeatTunnelServeRes interface {
	heartbeatTunnelServeRes()
}

type ListAccountsRes interface {
	listAccountsRes()
}

type ListAdminWorkgroupsRes interface {
	listAdminWorkgroupsRes()
}

type ListAdvertisementsRes interface {
	listAdvertisementsRes()
}

type ListAuditEventsRes interface {
	listAuditEventsRes()
}

type ListContractsRes interface {
	listContractsRes()
}

type ListEnvironmentsRes interface {
	listEnvironmentsRes()
}

type ListOrganizationsRes interface {
	listOrganizationsRes()
}

type ListSessionsRes interface {
	listSessionsRes()
}

type ListTunnelAttachmentsRes interface {
	listTunnelAttachmentsRes()
}

type ListTunnelGrantsRes interface {
	listTunnelGrantsRes()
}

type ListTunnelsRes interface {
	listTunnelsRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type ListWorkgroupMembersRes interface {
	listWorkgroupMembersRes()
}

type ListWorkgroupsRes interface {
	listWorkgroupsRes()
}

type LoginRes interface {
	loginRes()
}

type ProposeSessionRes interface {
	proposeSessionRes()
}

type PublishAdvertisementRes interface {
	publishAdvertisementRes()
}

type RegenerateAccountTokenRes interface {
	regenerateAccountTokenRes()
}

type RejectSessionRes interface {
	rejectSessionRes()
}

type RemoveTunnelGrantRes interface {
	removeTunnelGrantRes()
}

type RemoveWorkgroupMemberRes interface {
	removeWorkgroupMemberRes()
}

type ReportSessionEnvelopeCountRes interface {
	reportSessionEnvelopeCountRes()
}

type RetractAdvertisementRes interface {
	retractAdvertisementRes()
}

type SearchCatalogRes interface {
	searchCatalogRes()
}

type StartTunnelServeRes interface {
	startTunnelServeRes()
}

type TakeoverTunnelRes interface {
	takeoverTunnelRes()
}

type UpdateAdvertisementRes interface {
	updateAdvertisementRes()
}

type UpdateContractRes interface {
	updateContractRes()
}

type WhoamiRes interface {
	whoamiRes()
}
