// Code generated by ogen, DO NOT EDIT.
package api

type ChangePasswordRes interface {
	changePasswordRes()
}

type CreateAccountRes interface {
	createAccountRes()
}

type CreateEnvironmentRes interface {
	createEnvironmentRes()
}

type CreateOrganizationRes interface {
	createOrganizationRes()
}

type CreateTunnelRes interface {
	createTunnelRes()
}

type DeleteEnvironmentRes interface {
	deleteEnvironmentRes()
}

type DeleteTunnelRes interface {
	deleteTunnelRes()
}

type GetEnvironmentRes interface {
	getEnvironmentRes()
}

type GetTunnelRes interface {
	getTunnelRes()
}

type ListAccountsRes interface {
	listAccountsRes()
}

type ListEnvironmentsRes interface {
	listEnvironmentsRes()
}

type ListOrganizationsRes interface {
	listOrganizationsRes()
}

type ListTunnelsRes interface {
	listTunnelsRes()
}

type LoginRes interface {
	loginRes()
}

type RegenerateAccountTokenRes interface {
	regenerateAccountTokenRes()
}
