// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CreateAccountParams is parameters of createAccount operation.
type CreateAccountParams struct {
	OrganizationId uuid.UUID
}

func unpackCreateAccountParams(packed middleware.Parameters) (params CreateAccountParams) {
	{
		key := middleware.ParameterKey{
			Name: "organizationId",
			In:   "path",
		}
		params.OrganizationId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCreateAccountParams(args [1]string, argsEscaped bool, r *http.Request) (params CreateAccountParams, _ error) {
	// Decode path: organizationId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "organizationId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrganizationId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "organizationId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteEnvironmentParams is parameters of deleteEnvironment operation.
type DeleteEnvironmentParams struct {
	EnvironmentId uuid.UUID
}

func unpackDeleteEnvironmentParams(packed middleware.Parameters) (params DeleteEnvironmentParams) {
	{
		key := middleware.ParameterKey{
			Name: "environmentId",
			In:   "path",
		}
		params.EnvironmentId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteEnvironmentParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteEnvironmentParams, _ error) {
	// Decode path: environmentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "environmentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.EnvironmentId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "environmentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteTunnelParams is parameters of deleteTunnel operation.
type DeleteTunnelParams struct {
	TunnelId uuid.UUID
}

func unpackDeleteTunnelParams(packed middleware.Parameters) (params DeleteTunnelParams) {
	{
		key := middleware.ParameterKey{
			Name: "tunnelId",
			In:   "path",
		}
		params.TunnelId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteTunnelParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteTunnelParams, _ error) {
	// Decode path: tunnelId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "tunnelId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TunnelId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tunnelId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetEnvironmentParams is parameters of getEnvironment operation.
type GetEnvironmentParams struct {
	EnvironmentId uuid.UUID
}

func unpackGetEnvironmentParams(packed middleware.Parameters) (params GetEnvironmentParams) {
	{
		key := middleware.ParameterKey{
			Name: "environmentId",
			In:   "path",
		}
		params.EnvironmentId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetEnvironmentParams(args [1]string, argsEscaped bool, r *http.Request) (params GetEnvironmentParams, _ error) {
	// Decode path: environmentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "environmentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.EnvironmentId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "environmentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTunnelParams is parameters of getTunnel operation.
type GetTunnelParams struct {
	TunnelId uuid.UUID
}

func unpackGetTunnelParams(packed middleware.Parameters) (params GetTunnelParams) {
	{
		key := middleware.ParameterKey{
			Name: "tunnelId",
			In:   "path",
		}
		params.TunnelId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetTunnelParams(args [1]string, argsEscaped bool, r *http.Request) (params GetTunnelParams, _ error) {
	// Decode path: tunnelId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "tunnelId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TunnelId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tunnelId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListAccountsParams is parameters of listAccounts operation.
type ListAccountsParams struct {
	OrganizationId uuid.UUID
}

func unpackListAccountsParams(packed middleware.Parameters) (params ListAccountsParams) {
	{
		key := middleware.ParameterKey{
			Name: "organizationId",
			In:   "path",
		}
		params.OrganizationId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeListAccountsParams(args [1]string, argsEscaped bool, r *http.Request) (params ListAccountsParams, _ error) {
	// Decode path: organizationId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "organizationId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrganizationId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "organizationId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
