// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AddTunnelGrantParams is parameters of addTunnelGrant operation.
type AddTunnelGrantParams struct {
	TunnelId string
}

func unpackAddTunnelGrantParams(packed middleware.Parameters) (params AddTunnelGrantParams) {
	{
		key := middleware.ParameterKey{
			Name: "tunnelId",
			In:   "path",
		}
		params.TunnelId = packed[key].(string)
	}
	return params
}

func decodeAddTunnelGrantParams(args [1]string, argsEscaped bool, r *http.Request) (params AddTunnelGrantParams, _ error) {
	// Decode path: tunnelId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "tunnelId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.TunnelId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^tt_[a-z0-9]{12}$"],
				}).Validate(string(params.TunnelId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tunnelId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CreateAccountParams is parameters of createAccount operation.
type CreateAccountParams struct {
	OrganizationId string
}

func unpackCreateAccountParams(packed middleware.Parameters) (params CreateAccountParams) {
	{
		key := middleware.ParameterKey{
			Name: "organizationId",
			In:   "path",
		}
		params.OrganizationId = packed[key].(string)
	}
	return params
}

func decodeCreateAccountParams(args [1]string, argsEscaped bool, r *http.Request) (params CreateAccountParams, _ error) {
	// Decode path: organizationId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "organizationId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrganizationId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^org_[a-z0-9]{12}$"],
				}).Validate(string(params.OrganizationId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "organizationId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteAccountParams is parameters of deleteAccount operation.
type DeleteAccountParams struct {
	OrganizationId string
	AccountId      string
}

func unpackDeleteAccountParams(packed middleware.Parameters) (params DeleteAccountParams) {
	{
		key := middleware.ParameterKey{
			Name: "organizationId",
			In:   "path",
		}
		params.OrganizationId = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "accountId",
			In:   "path",
		}
		params.AccountId = packed[key].(string)
	}
	return params
}

func decodeDeleteAccountParams(args [2]string, argsEscaped bool, r *http.Request) (params DeleteAccountParams, _ error) {
	// Decode path: organizationId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "organizationId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrganizationId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^org_[a-z0-9]{12}$"],
				}).Validate(string(params.OrganizationId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "organizationId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: accountId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "accountId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^ac_[a-z0-9]{12}$"],
				}).Validate(string(params.AccountId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "accountId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteOrganizationParams is parameters of deleteOrganization operation.
type DeleteOrganizationParams struct {
	OrganizationId string
}

func unpackDeleteOrganizationParams(packed middleware.Parameters) (params DeleteOrganizationParams) {
	{
		key := middleware.ParameterKey{
			Name: "organizationId",
			In:   "path",
		}
		params.OrganizationId = packed[key].(string)
	}
	return params
}

func decodeDeleteOrganizationParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteOrganizationParams, _ error) {
	// Decode path: organizationId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "organizationId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrganizationId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^org_[a-z0-9]{12}$"],
				}).Validate(string(params.OrganizationId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "organizationId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteTunnelParams is parameters of deleteTunnel operation.
type DeleteTunnelParams struct {
	TunnelId string
}

func unpackDeleteTunnelParams(packed middleware.Parameters) (params DeleteTunnelParams) {
	{
		key := middleware.ParameterKey{
			Name: "tunnelId",
			In:   "path",
		}
		params.TunnelId = packed[key].(string)
	}
	return params
}

func decodeDeleteTunnelParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteTunnelParams, _ error) {
	// Decode path: tunnelId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "tunnelId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.TunnelId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^tt_[a-z0-9]{12}$"],
				}).Validate(string(params.TunnelId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tunnelId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteTunnelAttachmentParams is parameters of deleteTunnelAttachment operation.
type DeleteTunnelAttachmentParams struct {
	AttachmentId string
}

func unpackDeleteTunnelAttachmentParams(packed middleware.Parameters) (params DeleteTunnelAttachmentParams) {
	{
		key := middleware.ParameterKey{
			Name: "attachmentId",
			In:   "path",
		}
		params.AttachmentId = packed[key].(string)
	}
	return params
}

func decodeDeleteTunnelAttachmentParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteTunnelAttachmentParams, _ error) {
	// Decode path: attachmentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "attachmentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AttachmentId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^ta_[a-z0-9]{12}$"],
				}).Validate(string(params.AttachmentId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "attachmentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteTunnelServeParams is parameters of deleteTunnelServe operation.
type DeleteTunnelServeParams struct {
	ServeId string
}

func unpackDeleteTunnelServeParams(packed middleware.Parameters) (params DeleteTunnelServeParams) {
	{
		key := middleware.ParameterKey{
			Name: "serveId",
			In:   "path",
		}
		params.ServeId = packed[key].(string)
	}
	return params
}

func decodeDeleteTunnelServeParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteTunnelServeParams, _ error) {
	// Decode path: serveId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "serveId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ServeId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^ts_[a-z0-9]{12}$"],
				}).Validate(string(params.ServeId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "serveId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DisableEnvironmentParams is parameters of disableEnvironment operation.
type DisableEnvironmentParams struct {
	EnvironmentId string
}

func unpackDisableEnvironmentParams(packed middleware.Parameters) (params DisableEnvironmentParams) {
	{
		key := middleware.ParameterKey{
			Name: "environmentId",
			In:   "path",
		}
		params.EnvironmentId = packed[key].(string)
	}
	return params
}

func decodeDisableEnvironmentParams(args [1]string, argsEscaped bool, r *http.Request) (params DisableEnvironmentParams, _ error) {
	// Decode path: environmentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "environmentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.EnvironmentId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^ev_[a-z0-9]{12}$"],
				}).Validate(string(params.EnvironmentId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "environmentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetEnvironmentParams is parameters of getEnvironment operation.
type GetEnvironmentParams struct {
	EnvironmentId string
}

func unpackGetEnvironmentParams(packed middleware.Parameters) (params GetEnvironmentParams) {
	{
		key := middleware.ParameterKey{
			Name: "environmentId",
			In:   "path",
		}
		params.EnvironmentId = packed[key].(string)
	}
	return params
}

func decodeGetEnvironmentParams(args [1]string, argsEscaped bool, r *http.Request) (params GetEnvironmentParams, _ error) {
	// Decode path: environmentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "environmentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.EnvironmentId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^ev_[a-z0-9]{12}$"],
				}).Validate(string(params.EnvironmentId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "environmentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTunnelParams is parameters of getTunnel operation.
type GetTunnelParams struct {
	TunnelId string
}

func unpackGetTunnelParams(packed middleware.Parameters) (params GetTunnelParams) {
	{
		key := middleware.ParameterKey{
			Name: "tunnelId",
			In:   "path",
		}
		params.TunnelId = packed[key].(string)
	}
	return params
}

func decodeGetTunnelParams(args [1]string, argsEscaped bool, r *http.Request) (params GetTunnelParams, _ error) {
	// Decode path: tunnelId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "tunnelId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.TunnelId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^tt_[a-z0-9]{12}$"],
				}).Validate(string(params.TunnelId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tunnelId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// HeartbeatEnvironmentParams is parameters of heartbeatEnvironment operation.
type HeartbeatEnvironmentParams struct {
	EnvironmentId string
}

func unpackHeartbeatEnvironmentParams(packed middleware.Parameters) (params HeartbeatEnvironmentParams) {
	{
		key := middleware.ParameterKey{
			Name: "environmentId",
			In:   "path",
		}
		params.EnvironmentId = packed[key].(string)
	}
	return params
}

func decodeHeartbeatEnvironmentParams(args [1]string, argsEscaped bool, r *http.Request) (params HeartbeatEnvironmentParams, _ error) {
	// Decode path: environmentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "environmentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.EnvironmentId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^ev_[a-z0-9]{12}$"],
				}).Validate(string(params.EnvironmentId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "environmentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// HeartbeatTunnelAttachmentParams is parameters of heartbeatTunnelAttachment operation.
type HeartbeatTunnelAttachmentParams struct {
	AttachmentId string
}

func unpackHeartbeatTunnelAttachmentParams(packed middleware.Parameters) (params HeartbeatTunnelAttachmentParams) {
	{
		key := middleware.ParameterKey{
			Name: "attachmentId",
			In:   "path",
		}
		params.AttachmentId = packed[key].(string)
	}
	return params
}

func decodeHeartbeatTunnelAttachmentParams(args [1]string, argsEscaped bool, r *http.Request) (params HeartbeatTunnelAttachmentParams, _ error) {
	// Decode path: attachmentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "attachmentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AttachmentId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^ta_[a-z0-9]{12}$"],
				}).Validate(string(params.AttachmentId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "attachmentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// HeartbeatTunnelServeParams is parameters of heartbeatTunnelServe operation.
type HeartbeatTunnelServeParams struct {
	ServeId string
}

func unpackHeartbeatTunnelServeParams(packed middleware.Parameters) (params HeartbeatTunnelServeParams) {
	{
		key := middleware.ParameterKey{
			Name: "serveId",
			In:   "path",
		}
		params.ServeId = packed[key].(string)
	}
	return params
}

func decodeHeartbeatTunnelServeParams(args [1]string, argsEscaped bool, r *http.Request) (params HeartbeatTunnelServeParams, _ error) {
	// Decode path: serveId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "serveId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ServeId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^ts_[a-z0-9]{12}$"],
				}).Validate(string(params.ServeId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "serveId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListAccountsParams is parameters of listAccounts operation.
type ListAccountsParams struct {
	OrganizationId string
}

func unpackListAccountsParams(packed middleware.Parameters) (params ListAccountsParams) {
	{
		key := middleware.ParameterKey{
			Name: "organizationId",
			In:   "path",
		}
		params.OrganizationId = packed[key].(string)
	}
	return params
}

func decodeListAccountsParams(args [1]string, argsEscaped bool, r *http.Request) (params ListAccountsParams, _ error) {
	// Decode path: organizationId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "organizationId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrganizationId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^org_[a-z0-9]{12}$"],
				}).Validate(string(params.OrganizationId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "organizationId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListTunnelAttachmentsParams is parameters of listTunnelAttachments operation.
type ListTunnelAttachmentsParams struct {
	TunnelId string
}

func unpackListTunnelAttachmentsParams(packed middleware.Parameters) (params ListTunnelAttachmentsParams) {
	{
		key := middleware.ParameterKey{
			Name: "tunnelId",
			In:   "path",
		}
		params.TunnelId = packed[key].(string)
	}
	return params
}

func decodeListTunnelAttachmentsParams(args [1]string, argsEscaped bool, r *http.Request) (params ListTunnelAttachmentsParams, _ error) {
	// Decode path: tunnelId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "tunnelId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.TunnelId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^tt_[a-z0-9]{12}$"],
				}).Validate(string(params.TunnelId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tunnelId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListTunnelGrantsParams is parameters of listTunnelGrants operation.
type ListTunnelGrantsParams struct {
	TunnelId string
}

func unpackListTunnelGrantsParams(packed middleware.Parameters) (params ListTunnelGrantsParams) {
	{
		key := middleware.ParameterKey{
			Name: "tunnelId",
			In:   "path",
		}
		params.TunnelId = packed[key].(string)
	}
	return params
}

func decodeListTunnelGrantsParams(args [1]string, argsEscaped bool, r *http.Request) (params ListTunnelGrantsParams, _ error) {
	// Decode path: tunnelId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "tunnelId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.TunnelId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^tt_[a-z0-9]{12}$"],
				}).Validate(string(params.TunnelId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tunnelId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListTunnelsParams is parameters of listTunnels operation.
type ListTunnelsParams struct {
	Scope OptListTunnelsScope
}

func unpackListTunnelsParams(packed middleware.Parameters) (params ListTunnelsParams) {
	{
		key := middleware.ParameterKey{
			Name: "scope",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Scope = v.(OptListTunnelsScope)
		}
	}
	return params
}

func decodeListTunnelsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListTunnelsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: scope.
	{
		val := ListTunnelsScope("owned")
		params.Scope.SetTo(val)
	}
	// Decode query: scope.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "scope",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotScopeVal ListTunnelsScope
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotScopeVal = ListTunnelsScope(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Scope.SetTo(paramsDotScopeVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Scope.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "scope",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListUsersParams is parameters of listUsers operation.
type ListUsersParams struct {
	OrganizationId OptString
}

func unpackListUsersParams(packed middleware.Parameters) (params ListUsersParams) {
	{
		key := middleware.ParameterKey{
			Name: "organizationId",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.OrganizationId = v.(OptString)
		}
	}
	return params
}

func decodeListUsersParams(args [0]string, argsEscaped bool, r *http.Request) (params ListUsersParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: organizationId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "organizationId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOrganizationIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotOrganizationIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.OrganizationId.SetTo(paramsDotOrganizationIdVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.OrganizationId.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:    0,
							MinLengthSet: false,
							MaxLength:    0,
							MaxLengthSet: false,
							Email:        false,
							Hostname:     false,
							Regex:        regexMap["^org_[a-z0-9]{12}$"],
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "organizationId",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// RemoveTunnelGrantParams is parameters of removeTunnelGrant operation.
type RemoveTunnelGrantParams struct {
	TunnelId  string
	AccountId string
}

func unpackRemoveTunnelGrantParams(packed middleware.Parameters) (params RemoveTunnelGrantParams) {
	{
		key := middleware.ParameterKey{
			Name: "tunnelId",
			In:   "path",
		}
		params.TunnelId = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "accountId",
			In:   "path",
		}
		params.AccountId = packed[key].(string)
	}
	return params
}

func decodeRemoveTunnelGrantParams(args [2]string, argsEscaped bool, r *http.Request) (params RemoveTunnelGrantParams, _ error) {
	// Decode path: tunnelId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "tunnelId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.TunnelId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^tt_[a-z0-9]{12}$"],
				}).Validate(string(params.TunnelId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tunnelId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: accountId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "accountId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^ac_[a-z0-9]{12}$"],
				}).Validate(string(params.AccountId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "accountId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// StartTunnelServeParams is parameters of startTunnelServe operation.
type StartTunnelServeParams struct {
	TunnelId string
}

func unpackStartTunnelServeParams(packed middleware.Parameters) (params StartTunnelServeParams) {
	{
		key := middleware.ParameterKey{
			Name: "tunnelId",
			In:   "path",
		}
		params.TunnelId = packed[key].(string)
	}
	return params
}

func decodeStartTunnelServeParams(args [1]string, argsEscaped bool, r *http.Request) (params StartTunnelServeParams, _ error) {
	// Decode path: tunnelId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "tunnelId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.TunnelId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^tt_[a-z0-9]{12}$"],
				}).Validate(string(params.TunnelId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tunnelId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
