// Code generated by ogen, DO NOT EDIT.
package api

type AcceptWorkgroupInvitationRes interface {
	acceptWorkgroupInvitationRes()
}

type AddTunnelGrantRes interface {
	addTunnelGrantRes()
}

type AddWorkgroupMemberRes interface {
	addWorkgroupMemberRes()
}

type ChangePasswordRes interface {
	changePasswordRes()
}

type ChangeWorkgroupMembershipRoleRes interface {
	changeWorkgroupMembershipRoleRes()
}

type ConnectTunnelRes interface {
	connectTunnelRes()
}

type CreateAccountRes interface {
	createAccountRes()
}

type CreateOrganizationRes interface {
	createOrganizationRes()
}

type CreateTunnelRes interface {
	createTunnelRes()
}

type CreateWorkgroupRes interface {
	createWorkgroupRes()
}

type DeclineWorkgroupInvitationRes interface {
	declineWorkgroupInvitationRes()
}

type DeleteAccountRes interface {
	deleteAccountRes()
}

type DeleteOrganizationRes interface {
	deleteOrganizationRes()
}

type DeleteTunnelAttachmentRes interface {
	deleteTunnelAttachmentRes()
}

type DeleteTunnelRes interface {
	deleteTunnelRes()
}

type DeleteTunnelServeRes interface {
	deleteTunnelServeRes()
}

type DeleteWorkgroupRes interface {
	deleteWorkgroupRes()
}

type DisableEnvironmentRes interface {
	disableEnvironmentRes()
}

type EnableEnvironmentRes interface {
	enableEnvironmentRes()
}

type GetEnvironmentRes interface {
	getEnvironmentRes()
}

type GetTunnelRes interface {
	getTunnelRes()
}

type GetTunnelServeRes interface {
	getTunnelServeRes()
}

type GetWorkgroupRes interface {
	getWorkgroupRes()
}

type HeartbeatEnvironmentRes interface {
	heartbeatEnvironmentRes()
}

type HeartbeatTunnelAttachmentRes interface {
	heartbeatTunnelAttachmentRes()
}

type HeartbeatTunnelServeRes interface {
	heartbeatTunnelServeRes()
}

type ListAccountsRes interface {
	listAccountsRes()
}

type ListAdminWorkgroupsRes interface {
	listAdminWorkgroupsRes()
}

type ListEnvironmentsRes interface {
	listEnvironmentsRes()
}

type ListOrganizationsRes interface {
	listOrganizationsRes()
}

type ListTunnelAttachmentsRes interface {
	listTunnelAttachmentsRes()
}

type ListTunnelGrantsRes interface {
	listTunnelGrantsRes()
}

type ListTunnelsRes interface {
	listTunnelsRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type ListWorkgroupMembersRes interface {
	listWorkgroupMembersRes()
}

type ListWorkgroupsRes interface {
	listWorkgroupsRes()
}

type LoginRes interface {
	loginRes()
}

type RegenerateAccountTokenRes interface {
	regenerateAccountTokenRes()
}

type RemoveTunnelGrantRes interface {
	removeTunnelGrantRes()
}

type RemoveWorkgroupMemberRes interface {
	removeWorkgroupMemberRes()
}

type StartTunnelServeRes interface {
	startTunnelServeRes()
}
