// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/network/agent/pb/network.proto

package networkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeState int32

const (
	RuntimeState_RUNTIME_STATE_UNSPECIFIED RuntimeState = 0
	RuntimeState_RUNTIME_STATE_CONFIGURED  RuntimeState = 1
	RuntimeState_RUNTIME_STATE_STARTING    RuntimeState = 2
	RuntimeState_RUNTIME_STATE_RUNNING     RuntimeState = 3
	RuntimeState_RUNTIME_STATE_ERROR       RuntimeState = 4
	RuntimeState_RUNTIME_STATE_STOPPED     RuntimeState = 5
)

// Enum value maps for RuntimeState.
var (
	RuntimeState_name = map[int32]string{
		0: "RUNTIME_STATE_UNSPECIFIED",
		1: "RUNTIME_STATE_CONFIGURED",
		2: "RUNTIME_STATE_STARTING",
		3: "RUNTIME_STATE_RUNNING",
		4: "RUNTIME_STATE_ERROR",
		5: "RUNTIME_STATE_STOPPED",
	}
	RuntimeState_value = map[string]int32{
		"RUNTIME_STATE_UNSPECIFIED": 0,
		"RUNTIME_STATE_CONFIGURED":  1,
		"RUNTIME_STATE_STARTING":    2,
		"RUNTIME_STATE_RUNNING":     3,
		"RUNTIME_STATE_ERROR":       4,
		"RUNTIME_STATE_STOPPED":     5,
	}
)

func (x RuntimeState) Enum() *RuntimeState {
	p := new(RuntimeState)
	*p = x
	return p
}

func (x RuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_network_agent_pb_network_proto_enumTypes[0].Descriptor()
}

func (RuntimeState) Type() protoreflect.EnumType {
	return &file_internal_network_agent_pb_network_proto_enumTypes[0]
}

func (x RuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeState.Descriptor instead.
func (RuntimeState) EnumDescriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PingResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{2}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{3}
}

type ReloadEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadEnvironmentRequest) Reset() {
	*x = ReloadEnvironmentRequest{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadEnvironmentRequest) ProtoMessage() {}

func (x *ReloadEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*ReloadEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{4}
}

type ReloadEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *NetworkStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadEnvironmentResponse) Reset() {
	*x = ReloadEnvironmentResponse{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadEnvironmentResponse) ProtoMessage() {}

func (x *ReloadEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*ReloadEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{5}
}

func (x *ReloadEnvironmentResponse) GetStatus() *NetworkStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetNetworkStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkStatusRequest) Reset() {
	*x = GetNetworkStatusRequest{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkStatusRequest) ProtoMessage() {}

func (x *GetNetworkStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{6}
}

type GetNetworkStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *NetworkStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkStatusResponse) Reset() {
	*x = GetNetworkStatusResponse{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkStatusResponse) ProtoMessage() {}

func (x *GetNetworkStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkStatusResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{7}
}

func (x *GetNetworkStatusResponse) GetStatus() *NetworkStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DesiredServe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	BackendTarget string                 `protobuf:"bytes,4,opt,name=backend_target,json=backendTarget,proto3" json:"backend_target,omitempty"`
	GrantEmails   []string               `protobuf:"bytes,5,rep,name=grant_emails,json=grantEmails,proto3" json:"grant_emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredServe) Reset() {
	*x = DesiredServe{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredServe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredServe) ProtoMessage() {}

func (x *DesiredServe) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredServe.ProtoReflect.Descriptor instead.
func (*DesiredServe) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{8}
}

func (x *DesiredServe) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *DesiredServe) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DesiredServe) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *DesiredServe) GetBackendTarget() string {
	if x != nil {
		return x.BackendTarget
	}
	return ""
}

func (x *DesiredServe) GetGrantEmails() []string {
	if x != nil {
		return x.GrantEmails
	}
	return nil
}

type ManagedServeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Desired       *DesiredServe          `protobuf:"bytes,1,opt,name=desired,proto3" json:"desired,omitempty"`
	State         RuntimeState           `protobuf:"varint,2,opt,name=state,proto3,enum=agora.network.v1.RuntimeState" json:"state,omitempty"`
	TunnelId      string                 `protobuf:"bytes,3,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	ServeId       string                 `protobuf:"bytes,4,opt,name=serve_id,json=serveId,proto3" json:"serve_id,omitempty"`
	LastError     string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	LastStartedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_started_at,json=lastStartedAt,proto3" json:"last_started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedServeStatus) Reset() {
	*x = ManagedServeStatus{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedServeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedServeStatus) ProtoMessage() {}

func (x *ManagedServeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedServeStatus.ProtoReflect.Descriptor instead.
func (*ManagedServeStatus) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{9}
}

func (x *ManagedServeStatus) GetDesired() *DesiredServe {
	if x != nil {
		return x.Desired
	}
	return nil
}

func (x *ManagedServeStatus) GetState() RuntimeState {
	if x != nil {
		return x.State
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

func (x *ManagedServeStatus) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *ManagedServeStatus) GetServeId() string {
	if x != nil {
		return x.ServeId
	}
	return ""
}

func (x *ManagedServeStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ManagedServeStatus) GetLastStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStartedAt
	}
	return nil
}

type EnsureServeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	BackendTarget string                 `protobuf:"bytes,4,opt,name=backend_target,json=backendTarget,proto3" json:"backend_target,omitempty"`
	GrantEmails   []string               `protobuf:"bytes,5,rep,name=grant_emails,json=grantEmails,proto3" json:"grant_emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureServeRequest) Reset() {
	*x = EnsureServeRequest{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureServeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureServeRequest) ProtoMessage() {}

func (x *EnsureServeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureServeRequest.ProtoReflect.Descriptor instead.
func (*EnsureServeRequest) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{10}
}

func (x *EnsureServeRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *EnsureServeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnsureServeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *EnsureServeRequest) GetBackendTarget() string {
	if x != nil {
		return x.BackendTarget
	}
	return ""
}

func (x *EnsureServeRequest) GetGrantEmails() []string {
	if x != nil {
		return x.GrantEmails
	}
	return nil
}

type EnsureServeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serve         *ManagedServeStatus    `protobuf:"bytes,1,opt,name=serve,proto3" json:"serve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureServeResponse) Reset() {
	*x = EnsureServeResponse{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureServeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureServeResponse) ProtoMessage() {}

func (x *EnsureServeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureServeResponse.ProtoReflect.Descriptor instead.
func (*EnsureServeResponse) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{11}
}

func (x *EnsureServeResponse) GetServe() *ManagedServeStatus {
	if x != nil {
		return x.Serve
	}
	return nil
}

type RemoveServeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServeRequest) Reset() {
	*x = RemoveServeRequest{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServeRequest) ProtoMessage() {}

func (x *RemoveServeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServeRequest.ProtoReflect.Descriptor instead.
func (*RemoveServeRequest) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveServeRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *RemoveServeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveServeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServeResponse) Reset() {
	*x = RemoveServeResponse{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServeResponse) ProtoMessage() {}

func (x *RemoveServeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServeResponse.ProtoReflect.Descriptor instead.
func (*RemoveServeResponse) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{13}
}

type ListServesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServesRequest) Reset() {
	*x = ListServesRequest{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServesRequest) ProtoMessage() {}

func (x *ListServesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServesRequest.ProtoReflect.Descriptor instead.
func (*ListServesRequest) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{14}
}

type ListServesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serves        []*ManagedServeStatus  `protobuf:"bytes,1,rep,name=serves,proto3" json:"serves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServesResponse) Reset() {
	*x = ListServesResponse{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServesResponse) ProtoMessage() {}

func (x *ListServesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServesResponse.ProtoReflect.Descriptor instead.
func (*ListServesResponse) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{15}
}

func (x *ListServesResponse) GetServes() []*ManagedServeStatus {
	if x != nil {
		return x.Serves
	}
	return nil
}

type DesiredConnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ListenAddress string                 `protobuf:"bytes,3,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredConnect) Reset() {
	*x = DesiredConnect{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredConnect) ProtoMessage() {}

func (x *DesiredConnect) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredConnect.ProtoReflect.Descriptor instead.
func (*DesiredConnect) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{16}
}

func (x *DesiredConnect) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *DesiredConnect) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DesiredConnect) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

type ManagedConnectStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Desired       *DesiredConnect        `protobuf:"bytes,1,opt,name=desired,proto3" json:"desired,omitempty"`
	State         RuntimeState           `protobuf:"varint,2,opt,name=state,proto3,enum=agora.network.v1.RuntimeState" json:"state,omitempty"`
	TunnelId      string                 `protobuf:"bytes,3,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	AttachmentId  string                 `protobuf:"bytes,4,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	LastError     string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	LastStartedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_started_at,json=lastStartedAt,proto3" json:"last_started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedConnectStatus) Reset() {
	*x = ManagedConnectStatus{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedConnectStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedConnectStatus) ProtoMessage() {}

func (x *ManagedConnectStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedConnectStatus.ProtoReflect.Descriptor instead.
func (*ManagedConnectStatus) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{17}
}

func (x *ManagedConnectStatus) GetDesired() *DesiredConnect {
	if x != nil {
		return x.Desired
	}
	return nil
}

func (x *ManagedConnectStatus) GetState() RuntimeState {
	if x != nil {
		return x.State
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

func (x *ManagedConnectStatus) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *ManagedConnectStatus) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *ManagedConnectStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ManagedConnectStatus) GetLastStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStartedAt
	}
	return nil
}

type EnsureConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ListenAddress string                 `protobuf:"bytes,3,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureConnectRequest) Reset() {
	*x = EnsureConnectRequest{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureConnectRequest) ProtoMessage() {}

func (x *EnsureConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureConnectRequest.ProtoReflect.Descriptor instead.
func (*EnsureConnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{18}
}

func (x *EnsureConnectRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *EnsureConnectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnsureConnectRequest) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

type EnsureConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connect       *ManagedConnectStatus  `protobuf:"bytes,1,opt,name=connect,proto3" json:"connect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureConnectResponse) Reset() {
	*x = EnsureConnectResponse{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureConnectResponse) ProtoMessage() {}

func (x *EnsureConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureConnectResponse.ProtoReflect.Descriptor instead.
func (*EnsureConnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{19}
}

func (x *EnsureConnectResponse) GetConnect() *ManagedConnectStatus {
	if x != nil {
		return x.Connect
	}
	return nil
}

type RemoveConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ListenAddress string                 `protobuf:"bytes,3,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveConnectRequest) Reset() {
	*x = RemoveConnectRequest{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveConnectRequest) ProtoMessage() {}

func (x *RemoveConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveConnectRequest.ProtoReflect.Descriptor instead.
func (*RemoveConnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveConnectRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *RemoveConnectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoveConnectRequest) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

type RemoveConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveConnectResponse) Reset() {
	*x = RemoveConnectResponse{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveConnectResponse) ProtoMessage() {}

func (x *RemoveConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveConnectResponse.ProtoReflect.Descriptor instead.
func (*RemoveConnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{21}
}

type ListConnectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectsRequest) Reset() {
	*x = ListConnectsRequest{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectsRequest) ProtoMessage() {}

func (x *ListConnectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectsRequest.ProtoReflect.Descriptor instead.
func (*ListConnectsRequest) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{22}
}

type ListConnectsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Connects      []*ManagedConnectStatus `protobuf:"bytes,1,rep,name=connects,proto3" json:"connects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectsResponse) Reset() {
	*x = ListConnectsResponse{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectsResponse) ProtoMessage() {}

func (x *ListConnectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectsResponse) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{23}
}

func (x *ListConnectsResponse) GetConnects() []*ManagedConnectStatus {
	if x != nil {
		return x.Connects
	}
	return nil
}

type NetworkStatus struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Pid                int32                   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt          *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	SocketPath         string                  `protobuf:"bytes,3,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	EnvironmentEnabled bool                    `protobuf:"varint,4,opt,name=environment_enabled,json=environmentEnabled,proto3" json:"environment_enabled,omitempty"`
	EnvironmentId      string                  `protobuf:"bytes,5,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Serves             []*ManagedServeStatus   `protobuf:"bytes,6,rep,name=serves,proto3" json:"serves,omitempty"`
	Connects           []*ManagedConnectStatus `protobuf:"bytes,7,rep,name=connects,proto3" json:"connects,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NetworkStatus) Reset() {
	*x = NetworkStatus{}
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatus) ProtoMessage() {}

func (x *NetworkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_agent_pb_network_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStatus.ProtoReflect.Descriptor instead.
func (*NetworkStatus) Descriptor() ([]byte, []int) {
	return file_internal_network_agent_pb_network_proto_rawDescGZIP(), []int{24}
}

func (x *NetworkStatus) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NetworkStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *NetworkStatus) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *NetworkStatus) GetEnvironmentEnabled() bool {
	if x != nil {
		return x.EnvironmentEnabled
	}
	return false
}

func (x *NetworkStatus) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *NetworkStatus) GetServes() []*ManagedServeStatus {
	if x != nil {
		return x.Serves
	}
	return nil
}

func (x *NetworkStatus) GetConnects() []*ManagedConnectStatus {
	if x != nil {
		return x.Connects
	}
	return nil
}

var File_internal_network_agent_pb_network_proto protoreflect.FileDescriptor

const file_internal_network_agent_pb_network_proto_rawDesc = "" +
	"\n" +
	"'internal/network/agent/pb/network.proto\x12\x10agora.network.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vPingRequest\"[\n" +
	"\fPingResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\x1a\n" +
	"\x18ReloadEnvironmentRequest\"T\n" +
	"\x19ReloadEnvironmentResponse\x127\n" +
	"\x06status\x18\x01 \x01(\v2\x1f.agora.network.v1.NetworkStatusR\x06status\"\x19\n" +
	"\x17GetNetworkStatusRequest\"S\n" +
	"\x18GetNetworkStatusResponse\x127\n" +
	"\x06status\x18\x01 \x01(\v2\x1f.agora.network.v1.NetworkStatusR\x06status\"\x9d\x01\n" +
	"\fDesiredServe\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12%\n" +
	"\x0ebackend_target\x18\x04 \x01(\tR\rbackendTarget\x12!\n" +
	"\fgrant_emails\x18\x05 \x03(\tR\vgrantEmails\"\x9f\x02\n" +
	"\x12ManagedServeStatus\x128\n" +
	"\adesired\x18\x01 \x01(\v2\x1e.agora.network.v1.DesiredServeR\adesired\x124\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1e.agora.network.v1.RuntimeStateR\x05state\x12\x1b\n" +
	"\ttunnel_id\x18\x03 \x01(\tR\btunnelId\x12\x19\n" +
	"\bserve_id\x18\x04 \x01(\tR\aserveId\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x12B\n" +
	"\x0flast_started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastStartedAt\"\xa3\x01\n" +
	"\x12EnsureServeRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12%\n" +
	"\x0ebackend_target\x18\x04 \x01(\tR\rbackendTarget\x12!\n" +
	"\fgrant_emails\x18\x05 \x03(\tR\vgrantEmails\"Q\n" +
	"\x13EnsureServeResponse\x12:\n" +
	"\x05serve\x18\x01 \x01(\v2$.agora.network.v1.ManagedServeStatusR\x05serve\"E\n" +
	"\x12RemoveServeRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x15\n" +
	"\x13RemoveServeResponse\"\x13\n" +
	"\x11ListServesRequest\"R\n" +
	"\x12ListServesResponse\x12<\n" +
	"\x06serves\x18\x01 \x03(\v2$.agora.network.v1.ManagedServeStatusR\x06serves\"h\n" +
	"\x0eDesiredConnect\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0elisten_address\x18\x03 \x01(\tR\rlistenAddress\"\xad\x02\n" +
	"\x14ManagedConnectStatus\x12:\n" +
	"\adesired\x18\x01 \x01(\v2 .agora.network.v1.DesiredConnectR\adesired\x124\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1e.agora.network.v1.RuntimeStateR\x05state\x12\x1b\n" +
	"\ttunnel_id\x18\x03 \x01(\tR\btunnelId\x12#\n" +
	"\rattachment_id\x18\x04 \x01(\tR\fattachmentId\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x12B\n" +
	"\x0flast_started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastStartedAt\"n\n" +
	"\x14EnsureConnectRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0elisten_address\x18\x03 \x01(\tR\rlistenAddress\"Y\n" +
	"\x15EnsureConnectResponse\x12@\n" +
	"\aconnect\x18\x01 \x01(\v2&.agora.network.v1.ManagedConnectStatusR\aconnect\"n\n" +
	"\x14RemoveConnectRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0elisten_address\x18\x03 \x01(\tR\rlistenAddress\"\x17\n" +
	"\x15RemoveConnectResponse\"\x15\n" +
	"\x13ListConnectsRequest\"Z\n" +
	"\x14ListConnectsResponse\x12B\n" +
	"\bconnects\x18\x01 \x03(\v2&.agora.network.v1.ManagedConnectStatusR\bconnects\"\xd7\x02\n" +
	"\rNetworkStatus\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x1f\n" +
	"\vsocket_path\x18\x03 \x01(\tR\n" +
	"socketPath\x12/\n" +
	"\x13environment_enabled\x18\x04 \x01(\bR\x12environmentEnabled\x12%\n" +
	"\x0eenvironment_id\x18\x05 \x01(\tR\renvironmentId\x12<\n" +
	"\x06serves\x18\x06 \x03(\v2$.agora.network.v1.ManagedServeStatusR\x06serves\x12B\n" +
	"\bconnects\x18\a \x03(\v2&.agora.network.v1.ManagedConnectStatusR\bconnects*\xb6\x01\n" +
	"\fRuntimeState\x12\x1d\n" +
	"\x19RUNTIME_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RUNTIME_STATE_CONFIGURED\x10\x01\x12\x1a\n" +
	"\x16RUNTIME_STATE_STARTING\x10\x02\x12\x19\n" +
	"\x15RUNTIME_STATE_RUNNING\x10\x03\x12\x17\n" +
	"\x13RUNTIME_STATE_ERROR\x10\x04\x12\x19\n" +
	"\x15RUNTIME_STATE_STOPPED\x10\x052\xb7\a\n" +
	"\x0eNetworkService\x12E\n" +
	"\x04Ping\x12\x1d.agora.network.v1.PingRequest\x1a\x1e.agora.network.v1.PingResponse\x12Q\n" +
	"\bShutdown\x12!.agora.network.v1.ShutdownRequest\x1a\".agora.network.v1.ShutdownResponse\x12l\n" +
	"\x11ReloadEnvironment\x12*.agora.network.v1.ReloadEnvironmentRequest\x1a+.agora.network.v1.ReloadEnvironmentResponse\x12i\n" +
	"\x10GetNetworkStatus\x12).agora.network.v1.GetNetworkStatusRequest\x1a*.agora.network.v1.GetNetworkStatusResponse\x12Z\n" +
	"\vEnsureServe\x12$.agora.network.v1.EnsureServeRequest\x1a%.agora.network.v1.EnsureServeResponse\x12Z\n" +
	"\vRemoveServe\x12$.agora.network.v1.RemoveServeRequest\x1a%.agora.network.v1.RemoveServeResponse\x12W\n" +
	"\n" +
	"ListServes\x12#.agora.network.v1.ListServesRequest\x1a$.agora.network.v1.ListServesResponse\x12`\n" +
	"\rEnsureConnect\x12&.agora.network.v1.EnsureConnectRequest\x1a'.agora.network.v1.EnsureConnectResponse\x12`\n" +
	"\rRemoveConnect\x12&.agora.network.v1.RemoveConnectRequest\x1a'.agora.network.v1.RemoveConnectResponse\x12]\n" +
	"\fListConnects\x12%.agora.network.v1.ListConnectsRequest\x1a&.agora.network.v1.ListConnectsResponseB?Z=github.com/openziti/agora/internal/network/agent/pb;networkpbb\x06proto3"

var (
	file_internal_network_agent_pb_network_proto_rawDescOnce sync.Once
	file_internal_network_agent_pb_network_proto_rawDescData []byte
)

func file_internal_network_agent_pb_network_proto_rawDescGZIP() []byte {
	file_internal_network_agent_pb_network_proto_rawDescOnce.Do(func() {
		file_internal_network_agent_pb_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_network_agent_pb_network_proto_rawDesc), len(file_internal_network_agent_pb_network_proto_rawDesc)))
	})
	return file_internal_network_agent_pb_network_proto_rawDescData
}

var file_internal_network_agent_pb_network_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_network_agent_pb_network_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_internal_network_agent_pb_network_proto_goTypes = []any{
	(RuntimeState)(0),                 // 0: agora.network.v1.RuntimeState
	(*PingRequest)(nil),               // 1: agora.network.v1.PingRequest
	(*PingResponse)(nil),              // 2: agora.network.v1.PingResponse
	(*ShutdownRequest)(nil),           // 3: agora.network.v1.ShutdownRequest
	(*ShutdownResponse)(nil),          // 4: agora.network.v1.ShutdownResponse
	(*ReloadEnvironmentRequest)(nil),  // 5: agora.network.v1.ReloadEnvironmentRequest
	(*ReloadEnvironmentResponse)(nil), // 6: agora.network.v1.ReloadEnvironmentResponse
	(*GetNetworkStatusRequest)(nil),   // 7: agora.network.v1.GetNetworkStatusRequest
	(*GetNetworkStatusResponse)(nil),  // 8: agora.network.v1.GetNetworkStatusResponse
	(*DesiredServe)(nil),              // 9: agora.network.v1.DesiredServe
	(*ManagedServeStatus)(nil),        // 10: agora.network.v1.ManagedServeStatus
	(*EnsureServeRequest)(nil),        // 11: agora.network.v1.EnsureServeRequest
	(*EnsureServeResponse)(nil),       // 12: agora.network.v1.EnsureServeResponse
	(*RemoveServeRequest)(nil),        // 13: agora.network.v1.RemoveServeRequest
	(*RemoveServeResponse)(nil),       // 14: agora.network.v1.RemoveServeResponse
	(*ListServesRequest)(nil),         // 15: agora.network.v1.ListServesRequest
	(*ListServesResponse)(nil),        // 16: agora.network.v1.ListServesResponse
	(*DesiredConnect)(nil),            // 17: agora.network.v1.DesiredConnect
	(*ManagedConnectStatus)(nil),      // 18: agora.network.v1.ManagedConnectStatus
	(*EnsureConnectRequest)(nil),      // 19: agora.network.v1.EnsureConnectRequest
	(*EnsureConnectResponse)(nil),     // 20: agora.network.v1.EnsureConnectResponse
	(*RemoveConnectRequest)(nil),      // 21: agora.network.v1.RemoveConnectRequest
	(*RemoveConnectResponse)(nil),     // 22: agora.network.v1.RemoveConnectResponse
	(*ListConnectsRequest)(nil),       // 23: agora.network.v1.ListConnectsRequest
	(*ListConnectsResponse)(nil),      // 24: agora.network.v1.ListConnectsResponse
	(*NetworkStatus)(nil),             // 25: agora.network.v1.NetworkStatus
	(*timestamppb.Timestamp)(nil),     // 26: google.protobuf.Timestamp
}
var file_internal_network_agent_pb_network_proto_depIdxs = []int32{
	26, // 0: agora.network.v1.PingResponse.started_at:type_name -> google.protobuf.Timestamp
	25, // 1: agora.network.v1.ReloadEnvironmentResponse.status:type_name -> agora.network.v1.NetworkStatus
	25, // 2: agora.network.v1.GetNetworkStatusResponse.status:type_name -> agora.network.v1.NetworkStatus
	9,  // 3: agora.network.v1.ManagedServeStatus.desired:type_name -> agora.network.v1.DesiredServe
	0,  // 4: agora.network.v1.ManagedServeStatus.state:type_name -> agora.network.v1.RuntimeState
	26, // 5: agora.network.v1.ManagedServeStatus.last_started_at:type_name -> google.protobuf.Timestamp
	10, // 6: agora.network.v1.EnsureServeResponse.serve:type_name -> agora.network.v1.ManagedServeStatus
	10, // 7: agora.network.v1.ListServesResponse.serves:type_name -> agora.network.v1.ManagedServeStatus
	17, // 8: agora.network.v1.ManagedConnectStatus.desired:type_name -> agora.network.v1.DesiredConnect
	0,  // 9: agora.network.v1.ManagedConnectStatus.state:type_name -> agora.network.v1.RuntimeState
	26, // 10: agora.network.v1.ManagedConnectStatus.last_started_at:type_name -> google.protobuf.Timestamp
	18, // 11: agora.network.v1.EnsureConnectResponse.connect:type_name -> agora.network.v1.ManagedConnectStatus
	18, // 12: agora.network.v1.ListConnectsResponse.connects:type_name -> agora.network.v1.ManagedConnectStatus
	26, // 13: agora.network.v1.NetworkStatus.started_at:type_name -> google.protobuf.Timestamp
	10, // 14: agora.network.v1.NetworkStatus.serves:type_name -> agora.network.v1.ManagedServeStatus
	18, // 15: agora.network.v1.NetworkStatus.connects:type_name -> agora.network.v1.ManagedConnectStatus
	1,  // 16: agora.network.v1.NetworkService.Ping:input_type -> agora.network.v1.PingRequest
	3,  // 17: agora.network.v1.NetworkService.Shutdown:input_type -> agora.network.v1.ShutdownRequest
	5,  // 18: agora.network.v1.NetworkService.ReloadEnvironment:input_type -> agora.network.v1.ReloadEnvironmentRequest
	7,  // 19: agora.network.v1.NetworkService.GetNetworkStatus:input_type -> agora.network.v1.GetNetworkStatusRequest
	11, // 20: agora.network.v1.NetworkService.EnsureServe:input_type -> agora.network.v1.EnsureServeRequest
	13, // 21: agora.network.v1.NetworkService.RemoveServe:input_type -> agora.network.v1.RemoveServeRequest
	15, // 22: agora.network.v1.NetworkService.ListServes:input_type -> agora.network.v1.ListServesRequest
	19, // 23: agora.network.v1.NetworkService.EnsureConnect:input_type -> agora.network.v1.EnsureConnectRequest
	21, // 24: agora.network.v1.NetworkService.RemoveConnect:input_type -> agora.network.v1.RemoveConnectRequest
	23, // 25: agora.network.v1.NetworkService.ListConnects:input_type -> agora.network.v1.ListConnectsRequest
	2,  // 26: agora.network.v1.NetworkService.Ping:output_type -> agora.network.v1.PingResponse
	4,  // 27: agora.network.v1.NetworkService.Shutdown:output_type -> agora.network.v1.ShutdownResponse
	6,  // 28: agora.network.v1.NetworkService.ReloadEnvironment:output_type -> agora.network.v1.ReloadEnvironmentResponse
	8,  // 29: agora.network.v1.NetworkService.GetNetworkStatus:output_type -> agora.network.v1.GetNetworkStatusResponse
	12, // 30: agora.network.v1.NetworkService.EnsureServe:output_type -> agora.network.v1.EnsureServeResponse
	14, // 31: agora.network.v1.NetworkService.RemoveServe:output_type -> agora.network.v1.RemoveServeResponse
	16, // 32: agora.network.v1.NetworkService.ListServes:output_type -> agora.network.v1.ListServesResponse
	20, // 33: agora.network.v1.NetworkService.EnsureConnect:output_type -> agora.network.v1.EnsureConnectResponse
	22, // 34: agora.network.v1.NetworkService.RemoveConnect:output_type -> agora.network.v1.RemoveConnectResponse
	24, // 35: agora.network.v1.NetworkService.ListConnects:output_type -> agora.network.v1.ListConnectsResponse
	26, // [26:36] is the sub-list for method output_type
	16, // [16:26] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_internal_network_agent_pb_network_proto_init() }
func file_internal_network_agent_pb_network_proto_init() {
	if File_internal_network_agent_pb_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_network_agent_pb_network_proto_rawDesc), len(file_internal_network_agent_pb_network_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_network_agent_pb_network_proto_goTypes,
		DependencyIndexes: file_internal_network_agent_pb_network_proto_depIdxs,
		EnumInfos:         file_internal_network_agent_pb_network_proto_enumTypes,
		MessageInfos:      file_internal_network_agent_pb_network_proto_msgTypes,
	}.Build()
	File_internal_network_agent_pb_network_proto = out.File
	file_internal_network_agent_pb_network_proto_goTypes = nil
	file_internal_network_agent_pb_network_proto_depIdxs = nil
}
