package main

import (
	"encoding/json"
	"fmt"
	"math"
	"math/rand"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

type syntheticAuditEvent struct {
	OccurredAt      time.Time
	EventType       string
	OrganizationID  string
	AccountID       *string
	WorkgroupID     *string
	SessionID       *string
	AdvertisementID *string
	ContractID      *string
	EnvelopeID      *string
	Data            map[string]any
}

func synthesizeHistory(path string, duration time.Duration, topo *topology, orgIDs map[string]string, accounts map[string]seededAccount, workgroupIDs map[string]string, contractIDs map[string]string) (int, error) {
	if duration <= 0 {
		return 0, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return 0, err
	}

	providers := syntheticProviders(topo)
	consumer, ok := accounts["demo@agora.local"]
	if !ok {
		return 0, fmt.Errorf("synthetic history requires demo@agora.local account")
	}
	consumerOrgID := orgIDs[consumer.Spec.Organization]

	now := time.Now().UTC().Truncate(time.Hour)
	start := now.Add(-duration).Truncate(time.Hour)
	r := rand.New(rand.NewSource(now.Unix() / int64(time.Hour/time.Second)))
	events := make([]syntheticAuditEvent, 0, int(duration.Hours())*len(providers)*8)

	sessionSeq := 0
	for bucket := start; bucket.Before(now); bucket = bucket.Add(time.Hour) {
		activity := hourlyActivity(bucket)
		for _, provider := range providers {
			if r.Float64() > provider.Weight*activity {
				continue
			}
			sessionSeq++
			providerAccount := accounts[provider.Email]
			providerOrgID := orgIDs[providerAccount.Spec.Organization]
			workgroupID := workgroupIDs[provider.Workgroup]
			contractID := contractIDs[contractKey(provider.Email, provider.Contract)]
			if providerAccount.ID == "" || providerOrgID == "" || workgroupID == "" || contractID == "" {
				continue
			}
			adID := syntheticAdvertisementID(provider.AdvertisementName)
			sessionID := fmt.Sprintf("sess_seed_%012d", sessionSeq)
			countDelta := 8 + r.Intn(34)
			totalCount := countDelta
			proposedAt := bucket.Add(time.Duration(r.Intn(48)) * time.Minute)
			acceptedAt := proposedAt.Add(time.Duration(1+r.Intn(4)) * time.Second)
			flowedAt := acceptedAt.Add(time.Duration(30+r.Intn(150)) * time.Second)
			closedAt := flowedAt.Add(time.Duration(30+r.Intn(480)) * time.Second)
			closeReason := "consumer_close"
			closeDetail := "synthetic demo history normal close"
			if provider.Contract == "demo-contract-tight" && r.Float64() < 0.2 {
				closeReason = "contract_violation"
				closeDetail = "synthetic demo history tight-contract violation"
			}

			sessionData := map[string]any{
				"provider_account_id":      providerAccount.ID,
				"provider_organization_id": providerOrgID,
				"consumer_account_id":      consumer.ID,
				"consumer_organization_id": consumerOrgID,
				"tunnel_mode":              "tcp",
			}
			appendTwoParty(&events, proposedAt, "session.proposed", providerOrgID, providerAccount.ID, consumerOrgID, consumer.ID, workgroupID, sessionID, adID, "", sessionData)
			acceptedData := cloneData(sessionData)
			acceptedData["contract_id"] = contractID
			appendTwoParty(&events, acceptedAt, "session.accepted", providerOrgID, providerAccount.ID, consumerOrgID, consumer.ID, workgroupID, sessionID, adID, contractID, acceptedData)
			flowData := cloneData(sessionData)
			flowData["count_delta"] = countDelta
			flowData["total_count"] = totalCount
			appendTwoParty(&events, flowedAt, "envelope.flowed", providerOrgID, providerAccount.ID, consumerOrgID, consumer.ID, workgroupID, sessionID, adID, contractID, flowData)
			closedData := map[string]any{
				"provider_organization_id": providerOrgID,
				"consumer_organization_id": consumerOrgID,
				"close_reason":             closeReason,
				"close_detail":             closeDetail,
				"duration_seconds":         int64(closedAt.Sub(proposedAt).Seconds()),
			}
			if closeReason == "contract_violation" {
				closedData["violation_dimension"] = "max_duration"
			}
			appendTwoParty(&events, closedAt, "session.closed", providerOrgID, providerAccount.ID, consumerOrgID, consumer.ID, workgroupID, sessionID, adID, contractID, closedData)
		}
	}

	sort.Slice(events, func(i, j int) bool { return events[i].OccurredAt.Before(events[j].OccurredAt) })
	var b strings.Builder
	b.WriteString("-- Synthetic Agora dashboard history generated by demo-bootstrap.\n")
	b.WriteString("-- Load with psql -f after controller migrations have applied.\n")
	b.WriteString("begin;\n")
	for _, event := range events {
		line, err := renderAuditInsert(event)
		if err != nil {
			return 0, err
		}
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString("commit;\n")
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return 0, err
	}
	return len(events), nil
}

type syntheticProvider struct {
	Email             string
	AdvertisementName string
	Workgroup         string
	Contract          string
	Weight            float64
}

func syntheticProviders(topo *topology) []syntheticProvider {
	providers := make([]syntheticProvider, 0)
	for _, acct := range topo.Accounts {
		if acct.Gateway != "" || acct.Advertisement.Contract == "" {
			continue
		}
		weight := 0.4
		switch acct.Advertisement.Workgroup {
		case "markets-channel":
			weight = 0.62
		case "signals-channel":
			weight = 0.5
		case "weather-channel":
			weight = 0.34
		case "analytics-channel":
			weight = 0.44
		}
		providers = append(providers, syntheticProvider{
			Email:             acct.Email,
			AdvertisementName: acct.Advertisement.Name,
			Workgroup:         acct.Advertisement.Workgroup,
			Contract:          acct.Advertisement.Contract,
			Weight:            weight,
		})
	}
	return providers
}

func hourlyActivity(t time.Time) float64 {
	hour := t.Hour()
	business := math.Exp(-math.Pow(float64(hour-14), 2) / 38)
	morning := 0.35 * math.Exp(-math.Pow(float64(hour-9), 2)/18)
	overnight := 0.18
	activity := overnight + business + morning
	if t.Weekday() == time.Saturday || t.Weekday() == time.Sunday {
		activity *= 0.45
	}
	if activity > 1 {
		return 1
	}
	return activity
}

func appendTwoParty(events *[]syntheticAuditEvent, occurredAt time.Time, eventType, providerOrgID, providerAccountID, consumerOrgID, consumerAccountID, workgroupID, sessionID, advertisementID, contractID string, data map[string]any) {
	contractPtr := stringPtrOrNil(contractID)
	*events = append(*events, syntheticAuditEvent{
		OccurredAt:      occurredAt,
		EventType:       eventType,
		OrganizationID:  providerOrgID,
		AccountID:       stringPtrValue(providerAccountID),
		WorkgroupID:     stringPtrValue(workgroupID),
		SessionID:       stringPtrValue(sessionID),
		AdvertisementID: stringPtrValue(advertisementID),
		ContractID:      contractPtr,
		Data:            cloneData(data),
	})
	if providerOrgID == consumerOrgID {
		return
	}
	*events = append(*events, syntheticAuditEvent{
		OccurredAt:      occurredAt,
		EventType:       eventType,
		OrganizationID:  consumerOrgID,
		AccountID:       stringPtrValue(consumerAccountID),
		WorkgroupID:     stringPtrValue(workgroupID),
		SessionID:       stringPtrValue(sessionID),
		AdvertisementID: stringPtrValue(advertisementID),
		ContractID:      contractPtr,
		Data:            cloneData(data),
	})
}

func renderAuditInsert(event syntheticAuditEvent) (string, error) {
	data := event.Data
	if data == nil {
		data = map[string]any{}
	}
	encoded, err := json.Marshal(data)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf(
		"insert into audit_events (occurred_at, event_type, organization_id, account_id, workgroup_id, session_id, advertisement_id, contract_id, envelope_id, data) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb);",
		sqlString(event.OccurredAt.Format(time.RFC3339Nano)),
		sqlString(event.EventType),
		sqlString(event.OrganizationID),
		sqlStringPtr(event.AccountID),
		sqlStringPtr(event.WorkgroupID),
		sqlStringPtr(event.SessionID),
		sqlStringPtr(event.AdvertisementID),
		sqlStringPtr(event.ContractID),
		sqlStringPtr(event.EnvelopeID),
		sqlString(string(encoded)),
	), nil
}

func syntheticAdvertisementID(name string) string {
	cleaned := strings.NewReplacer("-", "", "_", "", "@", "", ".", "").Replace(name)
	if len(cleaned) > 12 {
		cleaned = cleaned[:12]
	}
	return "ad_seed_" + cleaned
}

func cloneData(data map[string]any) map[string]any {
	cloned := make(map[string]any, len(data))
	for k, v := range data {
		cloned[k] = v
	}
	return cloned
}

func stringPtrValue(v string) *string {
	return &v
}

func stringPtrOrNil(v string) *string {
	if v == "" {
		return nil
	}
	return &v
}

func sqlStringPtr(v *string) string {
	if v == nil {
		return "null"
	}
	return sqlString(*v)
}

func sqlString(v string) string {
	return "'" + strings.ReplaceAll(v, "'", "''") + "'"
}
